name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    if: github.event.release.draft == true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup LLVM
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm

      - name: Build
        shell: cmd
        run: build.cmd

      - name: Create Draft Release & Upload
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          files: |
            install.ps1
            langswitch.exe
